contracts/registry/ReverseRegistrar.sol
contracts/root/Controllable.sol
contracts/root/Root.sol
test/registry/TestReverseRegistrar.js

Adds Controller pattern to Reverse Registrar and adds a method to allow controllers to set any name to any reverse account node.
This PR will allow the permanent registrar controller (once added as a controller) to setName on behalf of a user
so then we can create a new register method on the permanent registrar controller that can call `setNameForAddr` and setup on the reverse record on behalf of a user. This will allow it to be all set in one tx on a new `register` function
30/6/21 addition:
Added functions as per @Arachnid's request to mirror the original functions so they can all be called with a custom address. Renamed them to `forAddr`.
`forAddr` functions can now be called by the address themselves, controller, or an authorised party on the ENS registry. The reason for adding …

Controller for Reverse Registrar

---

README.md

Markdown renderer doesn't consider em-dash as a list.

Fix rendering of resolver list in README

---

contracts/resolvers/profiles/ABIResolver.sol
contracts/resolvers/profiles/AddrResolver.sol
contracts/resolvers/profiles/ContentHashResolver.sol
contracts/resolvers/profiles/DNSResolver.sol
contracts/resolvers/profiles/InterfaceResolver.sol
contracts/resolvers/profiles/NameResolver.sol
contracts/resolvers/profiles/PubkeyResolver.sol
contracts/resolvers/profiles/TextResolver.sol

To increase their reuse in specific implementations (for example to optimize storage)

Adding virtual to methods in Resolver profiles

---

contracts/dnssec-oracle/DNSSEC.sol
contracts/dnssec-oracle/DNSSECImpl.sol

We are currently fixing a bug in the Solidity compiler where it did not properly enforce that the data location is unchanged during inheritance. This pull request fixes your contracts to be compliant with the stricter rules.
Your contracts can only be really affected by the bug when you have a contract that inherits from DNSSEC but not from DNSSECImpl, calls one of DNSSEC's functions internally and is part of an inheritance hierarchy that does include DNSSECImpl in the end, leading to virtual function lookup ending with the wrong data location of the passed arguments.
Here is a simplified example:
```solidity
abstract contract I {
function f(uint[] calldata x)  virtual internal;
}
contract C is I {
uint public data;
// The override checker in the compiler does not complain
// here - this …
```

Align data locations between interface and implementation.

---

contracts/wrapper/INameWrapper.sol
contracts/wrapper/NameWrapper.sol
test/ethregistrar/TestEthRegistrarController.js
test/wrapper/NameWrapper.js
test/wrapper/SupportsInterface.behaviour.js

This PR replaces the `CANNOT_REPLACE_SUBDOMAIN` fuse with a `PARENT_CANNOT_CONTROL` fuse, making it possible to lock individual subdomains against parental control, instead of locking them all.

Support locking individual child domains

---

test/dnssec-oracle/TestRRUtils.sol

As a general solidity rule, bytes are used for arbitrary-length raw byte data and string for arbitrary-length string (UTF-8) data. However testIterateRRs uses strings where bytes are expected. The test case is working only because of missing UTF-8 validation of array literal components in the solidity compiler. But, it is going to be fixed soon: https://github.com/ethereum/solidity/issues/13085.

Update testIterateRRs to use bytes instead of strings

---

deploy/ethregistrar/01_deploy_exponential_premium_price_oracle.ts
deploy/ethregistrar/02_deploy_legacy_eth_registrar_controller.ts
deploy/ethregistrar/03_deploy_eth_registrar_controller.ts

- previously if not on mainnet, StablePriceOracle was deployed
- this change uses ExponentialPremiumPriceOracle instead
- also updates the DummyOracle's constructor value to more accurately represent ETH/USD

add exponential premium price oracle to deploy scripts

---

contracts/utils/UniversalResolver.sol
deploy/utils/00_deploy_universal_resolver.ts
test/utils/TestUniversalResolver.js
test/utils/mocks/DummyOffchainResolver.sol

- iterates on #99 
- adds full ccip-read compatibility
- UniversalResolver requires batch gateway
- gateway urls can also be specified for each function call

Feature/full CCIP-read support in UniversalResolver

---

contracts/resolvers/PublicResolver.sol
test/resolvers/TestPublicResolver.js

The current version of the Public Resolver only allows owners to approve other addresses to update all of their records on their behalf. However, this proposed change (referred to as "token approvals") would allow an owner to approve a delegate to make changes to the records of a specific name. This would be useful for companies that want to retain control over their subnames but still allow employees to make updates to individual subnames assigned to them. For example, an employee could update all of the records for a subname like "greg.technet.eth," but the company would retain ownership and be able to revoke the approved wallet address at any time.
Another potential use case for token approvals is if a parent name is wrapped in a contract. In this scenario, the contract could approve …

Add token approvals to PublicResolver.sol

---

contracts/wrapper/ERC1155Fuse.sol
contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

1. Remove registrar.nameExpires() from everything and check expiry from getData() just like a normal wrapped name
1. renew() and wrapETH2LD() update expiry based onregistrar.nameExpires()`
1. renew()  if name is not wrapped** does not update eth expiry but just passes the call directly to registrar.renew and then returns without changing the state within the wrapper.
The idea is to not automatically update the expiry inside the wrapper by calling the registrar, but instead only updating it on wrapETH2LD() and renew(). This means if anyone calls the old controller, it will not extend expiry and allow them to use the name within wrapping.
**Not wrapped is defined as: `registrar.ownerOf()` OR `registry.owner()` are not the Name Wrapper contract OR `NameWrapper.ownerOf()` is zero`

Store eth expiry

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

* Add back in `isWrapped()` for `setSubnodeOwner/Record`
* Add protection against setting child fuses for unwrapped names in `setChildFuses()`
* Fix tests
* Add test to ensure TLDs can still be recovered if they expire via root calling ens.setSubnodeOwner()
Fixes:
https://github.com/code-423n4/2022-11-ens-findings/issues/14
https://github.com/code-423n4/2022-11-ens-findings/issues/16
These fixes were bundled together as they were written before Zhuo was officially added to the audit. They are also interrelated on the idea that: Names that are implicitly unwrapped need to be explicitly handled by the NameWrapper.
isWrapped() should understand when a subdomain has been unwrapped and needs to be re-wrapped. Even if it has been unwrapped by the parent using the registry.
For .eth names that …

Unwrapped burning protection

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

* Fixes issue where registering a previously wrapped name allows ownership on it in the NameWrapper

Prevent unwrapped names via re-registering previously wrapped names

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

1. Protects subdomains from being burnt whilst unexpired and then recreated (if CANNOT_CREATE_SUBDOMAIN) is already burnt
2. Protects subdomains from unexpiring and then being created again by a parent that has CANNOT_CREATE_SUBDOMAIN burnt
3. Retain the ability for subdomains to be unwrapped and retain their protection with PCC
Fixes:
https://github.com/code-423n4/2022-11-ens-findings/issues/8
https://github.com/code-423n4/2022-11-ens-findings/issues/7
Fixes merged as one PR as it affects whether or not a subdomain is considered "created" or not.

Mitigations for subnode creation

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

Checks for `CANNOT_TRANSFER` fuse when upgrading if `owner != newOwner`
Fixes: https://github.com/code-423n4/2022-11-ens-findings/issues/6

do preTransferCheck when owner != wrappedOwner on upgrade

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

Since the `setExpiry()` method does not alter fuses, perhaps this isn't needed. But I went ahead and added the `NameIsNotWrapped` changes that you made elsewhere for audit mitigations.

Preventing setExpiry from being called on unregistered/unwrapped names.

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

Mitigation for the following situation:
Name is wrapped, name is then renewed on the old controller (possibly unknowingly - using an old or 3rd party ui). Owner thinks that the name is expiring in a year, but actually it expires on the wrapper tomorrow. Name expires and now is lost/burnt because the NameWrapper owns it, but no one can actually get ownership unless it expires on the .eth registrar.

Allow expired names in wrapper but unexpired in registrar renew

---

contracts/ethregistrar/StablePriceOracle.sol

@jefflau //  None of the functions, including mul, div, sub, add, and mod, are used in this contract.

Remove SafeMath

---

index.js

Was upgrading from 0.0.8 to 0.0.17 and found this reference was broken. Based on dates, it may have been broken since 0.0.12 but I did not confirm.
I saw that there was another PR (#103), which is likely a better long-term solution, but wanted to get a quick fix up first.

Change BaseRegistrar and PriceOracle exports to IBaseRegistrar and IPriceOracle

---

contracts/wrapper/NameWrapper.sol
test/wrapper/NameWrapper.js

This PR addresses an issue with the setFuses function where previously set fuses were not being included in the returned result. A test has been added to ensure the returned fuses are accurate.

Fix setFuses return data

---

contracts/resolvers/profiles/IABIResolver.sol

The `IABIResolver` interface does not require any external solidity files.  These import statements can be removed.

Remove import statements from IABIResolver.sol

---

contracts/resolvers/PublicResolver.sol
contracts/wrapper/INameWrapper.sol
contracts/wrapper/NameWrapper.sol
test/wrapper/SupportsInterface.behaviour.js

This PR fixes a number of issues with the INameWrapper interface including:
- Removing a duplicate INameWrapper interface
- Adding missing functions to the INameWrapper, e.g. isWrapped
- Removing unnecessary interface override statements. 
In order to get the tests to pass I needed to clear old build data. I used:
```
rm -fr node_modules build cache artifacts
yarn
```
@jefflau

Fix Name Wrapper interface issues

---

test/wrapper/NameWrapper.js

This update serves the purpose of 
+ Adding two additional tests that showcase the functionality of the protection against extending expiries of unwrapped names.
+ Adding a new test that verifies if the approval information is successfully carried on upgrade.

Additional test for extendExpiry

---

contracts/wrapper/INameWrapper.sol
contracts/wrapper/INameWrapperUpgrade.sol
contracts/wrapper/NameWrapper.sol
contracts/wrapper/mocks/TestUnwrap.sol
contracts/wrapper/mocks/UpgradedNameWrapperMock.sol
test/wrapper/NameWrapper.js
test/wrapper/TestUnwrap.js

* Fixes an issue with extendExpiry that allows name to be burnt without resetting approve
* Fix issue with upgrade that didn't take into account approvals
* Add additional tests for the above issues
* Reduce the power of approvals to only allow access to extendExpiry
Thanks to @ZhangZhuoSJTU for the extra tests, and helping us find some issues with extendExpiry and upgrade

Reduce power of approve(). Protect extend and add approved to upgrade

---

contracts/resolvers/PublicResolver.sol

- When using ens-contracts as a submodule, having two versions of INameWrapper can cause problems.
@jefflau

Remove a duplicate copy of the INameWrapper interface. 

---

contracts/resolvers/Resolver.sol
contracts/utils/DummyOldResolver.sol
contracts/utils/UniversalResolver.sol
hardhat.config.ts
test/utils/TestUniversalResolver.js

previously, if the universalresolver's `_hasExtendedResolver()` function tried to call `supportsInterface()` on a contract without the function, it would always use the remaining gas for the function (calling invalid instruction = use all gas)
now the call to `supportsInterface()` has a manual gas limit of 50k, which is 10x normal usage so should be fine for edge cases as well. if the function doesn't exist the 50k gas limit will be used up instead of the limit of the whole call.

fix: universal resolver gas issues

---

contracts/utils/UniversalResolver.sol
test/utils/TestUniversalResolver.js

according to ENSIP-10, if using a resolver as a wildcard resolver it needs to support `resolve()`, otherwise it should revert.

fix: add wildcard support check in universal resolver

---

deploy/dnsregistrar/20_set_tlds.ts

`set_tlds` deploy script was broken. it wasn't picked up by the github action because it was being skipped.
changes:
- added tlds array for hardhat network (so that it runs on github actions)
- added dns encoded tld arg for the `enableNode()` function
- removed `Root` dep

fix: set_tlds deploy script
